id: "SBI-INIT-001"
title: ".deespec 標準構成のドキュメント化"
priority: 10
status: "done"
pbi_id: "0"
links:
  - "../../..//.deespec/README.md"
  - "../../../docs/DECISIONS_v1.md"
created_at: "2025-09-26T00:00:00Z"
updated_at: "2025-09-26T00:00:00Z"