name: release

on:
  push:
    branches:
      - main
    paths:
      - 'VERSION'

permissions:
  contents: write   # ← リリース作成に必須

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: "1.22" }

      - name: Read VERSION file
        id: version
        run: echo "VERSION=v$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          mkdir -p dist
          EXT=""
          if [ "${{ matrix.goos }}" = "windows" ]; then EXT=".exe"; fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} CGO_ENABLED=0 \
          go build -ldflags "-X github.com/YoshitsuguKoike/deespec/internal/buildinfo.Version=${{ steps.version.outputs.VERSION }}" \
            -o dist/deespec_${{ matrix.goos }}_${{ matrix.goarch }}$EXT ./cmd/deespec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deespec_${{ matrix.goos }}_${{ matrix.goarch }}
          path: dist/deespec_${{ matrix.goos }}_${{ matrix.goarch }}*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Read VERSION file
        id: version
        run: echo "VERSION=v$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: deespec_*
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.version.outputs.VERSION }}
          tag_name: ${{ steps.version.outputs.VERSION }}
          files: deespec_*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
